### ISSUE TITLE
[Feature] Export to csv button in reports

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Carson-s-Village#109]
**Feature Description**
A button that when clicked downloads the current report table as a CSV.

**Requirements**
- Export button
- On click, download and save CSV with title being a concise description of the search parameters, e.g. if the report is for a family the report would have a name 'family_report_2023-05-06'

**Comment by OfekShaltiel-UTD** [comment]
1. The export button and functionality already exist, should the button name be changed?
2. Is it fine to leave the format as the one provided by ``DateFormat()``?

**Comment by pariahGH** [comment]
if it already exists, we can mark this as done and just need to review the instruction manual to make sure we are as clear about it as possible.
for dates, the `yyyy-mm-dd` format will work fine everywhere

**Comment by OfekShaltiel-UTD** [comment]
These changes are in my last pr, so I'll let you close it if you are satisfied with it.
