### ISSUE TITLE
[Feature] Make an Archive Tab

### ISSUE THREAD

**Issue by FegelSamuel** [UTDallasEPICS/Carson-s-Village#114]
**Feature Description**
Jason said that the Advocate view is cluttered by the inactive / archived family pages. The desire of the feature is to eliminate this.

**Requirements**
Page will have archived family pages/ family report table entries.
Make sure that admin and advocates can re-enable pages if needed.
Family Reports page should have a toggle to only show active pages.

**Additional context**
Jason said that any UI for the solution is good as long as the clutter is removed.

**Comment by RajM16** [comment]
Archived Pages: UI design
one button to show all pages which sorts the reports by active and non active 
another toggle button for active and non active pages in one switch button
do same for pages view

**Comment by FegelSamuel** [comment]
Completed yesterday
