### ISSUE TITLE
[Feature] Advocate management system

### ISSUE THREAD

**Issue by OfekShaltiel-UTD** [UTDallasEPICS/Carson-s-Village#115]
**Feature Description**
Add enhancements to Advocate management system and role based access enhancement.

**Requirements**
- [x] improve requirements as current requirements are vague
- [x] clean up page list implementation (got it down to one api call for family and advocate pages and 3 others)
- [x] #219
- [x] finish admin view

**Additional context**
Changes to role based access following the introduction of UserVsFamily concept

**Comment by OfekShaltiel-UTD** [comment]
1. What should Admin/Jason see on his end for the page list? Is it every page in the site?
2. What should the user list page list consist of for Jason? The pages that were created by that user, right?
3.  Should we have a toggle for the family reports and page list to see every page at once or select by family?

**Comment by pariahGH** [comment]
for admins, we should have a dropdown that allows filtering by family. This will need to be emphasized in the UI so we may need to make it bigger, put a border around it, etc. 

yes, user list page list should show pages created by that user. 

i think what we can do, is if no family specified show all, if a family is specified then filter by that family

**Comment by OfekShaltiel-UTD** [comment]
That sounds great. I'll start on these changes tomorrow.

**Comment by OfekShaltiel-UTD** [comment]
I'm still planning to finish this one.
