### ISSUE TITLE
[Feature] Missing Stripe Integration Improvements 

### ISSUE THREAD

**Issue by OfekShaltiel-UTD** [UTDallasEPICS/Carson-s-Village#116]
**Feature Description**
The donation handling and donation management systems are mostly complete but are missing several features.

**Requirements**
- [x] Minimal family data to collect when onboarding onto Stripe Connect
- [x] Add Stripe fee calculation with toggle for donors to pay the fee themselves.

**Additional context**
Currently, families can onboard to Stripe Connect so that they can receive donated funds. However, the current setup uses standard accounts which takes too much form information from families. The information that we would like to minimize is business information for families.

# Links of Stripe fees
[Stripe pricing docs:](https://stripe.com/pricing)
[Stripe Connect Pricing docs:]( https://stripe.com/connect/pricing)

# Formulas
For Stripe Connect the fees are $0.25 + 0.25% per payout and $2 per active month per family account, and Stripe is 2.9% + $0.3 per transaction for donation entry. 

# Update
We are going for standard accounts which does not have fees for paying out donations and allows for prefilling of Carson's Village information.

**Comment by FegelSamuel** [comment]
This issue might require us to ask Jason about how we should approach creating a fee recovery **policy.**

**Comment by OfekShaltiel-UTD** [comment]
Still need support address to be autofiled, better UX for families Logging in and creating pages, need support for pages that do not receive donations.
