### ISSUE TITLE
[BUG] Searching pages with an empty value returns all the pages

### ISSUE THREAD

**Issue by FegelSamuel** [UTDallasEPICS/Carson-s-Village#121]
**Describe the bug**
Pressing the search button with nothing inside of it renders all the pages

**To Reproduce**
Use the search function with nothing inside of it

**Expected behavior**
We want this to return nothing when given nothing

**Additional context**
You can locate this file in anything that has a search function that looks up any page (definitely ask for help on this one).

**Comment by OfekShaltiel-UTD** [comment]
@pariahGH is this the intended behavior?

**Comment by FegelSamuel** [comment]
Jason said he didn't want the search to do that.

**Comment by OfekShaltiel-UTD** [comment]
Alright. I suppose returning all pages was an initial behavior for testing. We can make it return nothing for now unless Jason wants it otherwise.
