### ISSUE TITLE
[Feature] useFetch Conversion to $fetch

### ISSUE THREAD

**Issue by FegelSamuel** [UTDallasEPICS/Carson-s-Village#124]
**Feature Description**
We want to convert all useFetch() calls to #fetch when doing any User Interaction that isn't switching whole pages (the URL will change if the page is switched).

**Additional context**
* This is a Nuxt hook
* Taz mentioned to convert this to $fetch at yesterday's Vue workshop.

**Comment by OfekShaltiel-UTD** [comment]
This is a duplicate, unfortunately. My bad
