### ISSUE TITLE
[Feature] S24 Page Sorting

### ISSUE THREAD

**Issue by OfekShaltiel-UTD** [UTDallasEPICS/Carson-s-Village#125]
# Conceptual Overview
We need to be able to sort lists of things like pages. This applies to all lists in our application: Users list, pages list, FamilyReports, etc. For example, see [here](https://github.com/UTDallasEPICS/Carson-s-Village/blob/main/server/api/page_list.get.ts) and [here](https://github.com/UTDallasEPICS/Carson-s-Village/blob/main/pages/PageList/[id].vue)

# Technical Requirements
- must be able to sort all lists by every field via a sorting up and down button
- UI changes for indicating user sorting preferences

# Student Deliverables
- list of sortable fields for each list
- description of what functions need to be changed
- figma of UI changes
- working implementation

**Comment by FegelSamuel** [comment]
Josh + Kushika Completed this
