### ISSUE TITLE
[Feature] Backend code unification

### ISSUE THREAD

**Issue by OfekShaltiel-UTD** [UTDallasEPICS/Carson-s-Village#178]
**Feature Description**
After several years of using a Nuxt backend, the implementation of API endpoints has diverged.
Some api endpoints use ...body, some use body.attributeA, body.attributeB, ..., some use the body as { attributeA, attributeB,...,  data } and use ...data for database queries. The last one seems the most correct. 
**Requirements**
- [ ] Find one style of backend implementation. 
- [ ] Implement the backend style everywhere and test
- [x] Use the same prisma client instance everywhere, ``event.context.client``

**Comment by pariahGH** [comment]
`page.post.ts` is the recommended API implementation example
