### ISSUE TITLE
Fix folder structure

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Carson-s-Village#2]
- [x] nodev1, node-postgresql, etc should have their own branches labeled as archives or be in a single folder marked as archival
- [x] database folder can stay in top level
- [x] please no spaces in file/folder names, use _ or -
- [x] everything needs to actually be top level, dont use that single folder at the top level
- [x] #13
- [x] find out what data.csv is
- [x] fix .gitignores - node_modules should always be prohibited no matter what sub directory it ends up in - this is a point in favor of storing nodev1 etc on different branches

**Comment by RahulKolla** [comment]
removed folder
