### ISSUE TITLE
Tweak notes

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Carson-s-Village#203]
- [x] table pagination should show how many total pages there are
![image](https://github.com/user-attachments/assets/d249d4d8-de45-436c-93dc-af00fd38fb2b)

- [x] UI in family reports need to have the table centered
![image](https://github.com/user-attachments/assets/8d9321e1-b8ac-4d0b-9cbd-b4a0982df6c6)

- [x] CC list ID needs to be an ENV variable so we aren't hitting the same list in stage and production
- [x] Footer needs to be sticky to bottom of the page
- [x] investigate doing a sidebar instead of horizontal nav at the top, or otherwise shrink the size of nav options
- [x] when moving to NPTS, double check table mapped names
- [x] add ability to use existing user when creating a family instead of requiring a user to be created

**Comment by FegelSamuel** [comment]
test assigning ignore this
