### ISSUE TITLE
F24 - Reports Revamp

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Carson-s-Village#66]
# Conceptual Overview

We need to be able to export CSVs that yield information such as how many pages exist for each family, how much is owed/paid vs donation goals, and some synthetic statistics such as % goal reached for each page and who created that page.  

# Technical Requirements
- [x] page dedicated to reports, viewable by advocates and admin only
- [x] page must allow for selection of report dimensions
- [x]  page must allow for selection of date ranges
- [x]  page must export requested data as CSV

# Student deliverables
- [x] list of dimensions/metrics and how they are retrieved/generated
- [x]  figma of UI
- [x] Description of user journey with possible user interaction points
- [x] working implementation

**Comment by OfekShaltiel-UTD** [comment]
1. What are the minimum dimensions of the family reports table?
2. Are there columns that have to always remain on the table such as page name and status?
3. What date ranges are we filtering by? Donation deadline? Goal met dates? Start Dates?

**Comment by pariahGH** [comment]
1. TODO
2. name for sure, probably date created, deadline, and status we would want always there. 
3. All date fields should be orderable
4. we will want amount donated / donation goal, and i think for amount donated but not yet paid out that doesn't need to be a percentage

**Comment by FegelSamuel** [comment]
Basically done
