### ISSUE TITLE
F24 - List Sorting & Pagination

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Carson-s-Village#67]
# Conceptual Overview
We need to be able to sort lists of things like pages, while also supporting pagination. This applies to all lists in our application: Users list, pages list, etc. For example, see [here](https://github.com/UTDallasEPICS/Carson-s-Village/blob/main/server/api/page_list.get.ts) and [here](https://github.com/UTDallasEPICS/Carson-s-Village/blob/main/pages/PageList/[id].vue)

# Technical Requirements
- must be able to sort all lists by appropriate fields, to be determined
- UI changes for indicating user sorting preferences
- query results must be paginated - 12 results per page

# Student Deliverables
- list of sortable fields for each list
- description of what functions need to be changed
- figma of UI changes
- working implementation

**Comment by MStolen** [comment]
# Hint
### Related Prisma Docs
* [Pagination](https://www.prisma.io/docs/concepts/components/prisma-client/pagination)
* [Filtering and Sorting](https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting)

### Related Nuxt Documentation
* [useFetch](https://nuxt.com/docs/api/composables/use-fetch)
* [Requests with Query Parameters](https://nuxt.com/docs/guide/directory-structure/server#handling-requests-with-query-parameters)

**Comment by pariahGH** [comment]
![image](https://github.com/UTDallasEPICS/Carson-s-Village/assets/35643616/c84e2dab-dfdc-43e8-a668-7fc8541339a4)

Example of what a simple implementation could look like from a UX perspective. No need to track individual pages, the sorting and current/total counts should be enough. we will probably add text search to this as well.
