### ISSUE TITLE
F23 - Create payouts from inside our UI

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Carson-s-Village#68]
# Conceptual Overview
We need to be able to trigger payouts from inside our UI so that CV can manage everything about donations within the UI. Need to be able to payout for multiple pages at once to a given family, while still tracking each page's own payout status.

# Technical Requirements
- form for creating a payout to a family
- update payout tracking
- custom family onboarding 
# Student Deliverables
- figma for form
- working implementation
# Research Questions
- Does Stripe have an API function for grabbing the aggregate Stripe balance of Carson's Village? 
Yes, use an awaited stripe.Balance.retrieve().

- [x] users vs family concept is implemented to a usable point.
- [x] Link donation management page to families table instead of users table
- [x] Basic Family onboarding
- [ ] Custom Family onbaroding
- [x] Sending Payouts
- [x] Error handling

**Comment by OfekShaltiel-UTD** [comment]
1. Is this going to send the funds to Paypal or the family's bank account?
Answer: Everything is going through Stripe.
2. Are family members required to get a Stripe account?
3. If the system does send the funds to Paypal, will we store that on the users table?
4. How do we get information about the family's transaction method? Stripe Connect on boarding? Custom on boarding?

**Comment by pariahGH** [comment]
1. Funds are processed through Stripe - Stripe will move money from our account and wire it to the family's account.
2. Families do not need their own Stripe account - they will provide their banking info and a 'connected account' gets created in Stripe by our API for them: See [here](https://stripe.com/docs/connect/add-and-pay-out-guide?integration=with-code#with-code-create-connected-account) and [here](https://stripe.com/docs/api/external_accounts)
3. We will store the transaction id that Stripe returns to us, the date, the amount, and the corresponding page and family. We also need to include the user id that initiated the transfer.
4. We should be able to use Stripe's built in components for gathering user data. This will probably be very similar to how the existing donation workflow is setup.

**Comment by OfekShaltiel-UTD** [comment]
1. Since everything is going through Stripe Connect accounts 'connected accounts', do we want to store the Stripe account in the users table?
2. If the users have their Connected accounts in the users table what do we store? A stripe account object as its own table in the Database or as the account id of the connected account.

**Comment by pariahGH** [comment]
1. It will most likely be stored on the family, as opposed to users (once we break out the separate family vs user tables)
2. The family table will need a stripe account id column that maps to the stripe account
