### ISSUE TITLE
Donation Managment Page: Amount left to distribute to family page loses the cents sometimes.

### ISSUE THREAD

**Issue by OfekShaltiel-UTD** [UTDallasEPICS/Carson-s-Village#75]
The cents are accurate on the family but are specifically sometimes missing from the calculation on the family page.

**Comment by OfekShaltiel-UTD** [comment]
It was the page editing. The cents were lost due to the usage of parseInt on the incoming decimal amount raised. New push and PR with a bunch of fixes and improvements from the winter is coming by the end of today.

**Comment by FegelSamuel** [comment]
Is this issue resolved or should there be more work regarding it this semester?

**Comment by OfekShaltiel-UTD** [comment]
Yup. I fixed it.

**Comment by FegelSamuel** [comment]
Cool, I'll close the issue then.
