### ISSUE TITLE
F24 - Notes from jason

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Carson-s-Village#82]
## general navigation
 - [x] #142
 - provide clarity to users around hat each nav menu item actually means
 - integrate our menu system into existing carsons village design. this means bringing over that design to our system, reworking our nav to fit with it 

- [x] disable public page search, for now replace with a welcome statement: `“Welcome and thank you for
supporting one of the families in
our Village.` 
- [x] need to change authentication requirements for search, might become login only

- [x] columns for page list: page name, assigned advocate, total donated, goal, date created, deadline, creating user, and edit/view buttons. Ofek
- [ ] we might need to rework things so that advocate users can be 'assigned' to page users
- [x] separate the concept of users and families

## page editing
- [x]  change page name => name of deceased. re first/last, not all names are only first/last, change can be made but questions around accessibility 
- [x] need to rework how profile picture selection works
    -  he shouldnt have to ask,should just need some fiddlyt bits
- [x] add directions
- [x] visitation, goal optional
- [x] donation form not visible if past deadline

## Page & user lists
- [x] #149
- [x] family table toggle between families that have active pages vs inactive pages
## profile pages
- [x] user profile pages, name, address, phone, email 
- [ ] salesforce api integration? invite page should be just invite, not filling out profile info, another salesforce integration? 
- [] use SalesForce to automate large portions of page creation.

## donation management

- [x] donation management page list: add last donation date, date page created, page deadline status
- [ ] #150

## page view
- [x] make text bigger
- [ ] revisit layout (use existing as inpsiration)
- [x]  Auto image slideshow (keep controls, just auto move if not clicked) - [] Zooming animation for photos? -[] Image gallery pop up on family page
- [x] need to make progress bar and the percent goal complete bigger so its more visible 
- [x] donation form into button popup 
- [x] social share buttons
-  do we have a donation use text input?

answers to his questions:
-  distributions are recorded in our database with the stripe transaction ID
-  currently we dont mark specific donations as payed out, we just do the math on paying and payout, show the difference. when we add built in payout ability, we can probably link donations to a specific payout transaction in our DB.
-  currently pages are shown, we can add a filter for that

**Comment by pariahGH** [comment]
- Resources – Goes to [[https://carsonsvillage.org/#](https://carsonsvillage.org/)](https://carsonsvillage.org/ "https://carsonsvillage.org/#"), needs to be https://carsonsvillage.org/resource-library/
    
- About us – should go to https://carsonsvillage.org/about-us/
    
- we will need to account for processing fees when displaying payouts - minus a %
- nav links open in new tab
    
- header needs to match 
    
- search with empty value should not do anything at all
    
- revisit page layouts again esp with different amounts of text
    
- search bar in nav may be extraneous?
    
- UX around donation vs message vs donation message - these are two different things, do we need to drop one? carsons site seems to do both as distinct entities
    
- ability to update profile info?
    
- family page or memorial page?
    
- instructions for using dropdown to list pages
    
- page name => person name
    
- instructions around family creation - yes, create the family, assign the page to it
    
- instructions around profile picture select - maybe just rework this UX
    
- datepicker may be borked
    
- locationdoes not show up
    
- image CSS - fix stretching
    
- message form reset on submit
    
- users list needs to be actual user management
    
- double check admin invite
    
- family create UI needs to distinguish between family info vs info for inviting the first user - clarity around users vs families vs pages
    
- no page id in transaction list
    
- clarity around how funds distribution works - this is the payout from stripe to the family account
    
- clarity around how advocates are assigned to families - im the one that created the family and invited jason, so i show up
    
- goal date being reached doesnt trigger anything - manual toggle of archiving. need way to see archived/unarchived and unarchiving.

**Comment by pariahGH** [comment]
For directions in page editing:

- add a ? symbol (question-mark-circle from heroicons) to the label of each field
- the symbol can have a :title attribute containing some explanatory text

**Comment by OfekShaltiel-UTD** [comment]
Consolidated remainder into #188
