### ISSUE TITLE
F23 - users vs families

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Carson-s-Village#85]
- current user becomes family table
- new user table 
- user table has role column - an 'advocate' can load any family, any page, but 'users' can only load from families they are connected to, using the `usersOnFamilies` join table (`user.Families.map(({familyCuid}) => familyCuid).includes(family.cuid)`)
- Family creation should allow OPTIONAL inviting of the first user - so we send two things when we hit save, `familyData` and `possibleFirstUser`
- separate user invite page
- families list
- must be able to select which family a page is being made for (if user only connected to one family, then we dont need to show the select)
- 

- [x] Family Table
- [x] User Invite Changes
- [x] Admin role
- [x] Family invite flow
- [x] Pages linked to families
- [x] New Page list

**Comment by OfekShaltiel-UTD** [comment]
Current Schema Design/Mock Schema developed by Sholom and me.
model ConectedAccount {
  cuid                      String      @id @default(cuid())
  accountId              String     // Account id in Stripe in the form of (acct_XXXXXXXX)
  account_type          String   // Type of connected account: i.e. Express, Standard, or Custom
  account_status        String   // Active, inactive, etc.
  accountCapabilities  String[]   // The abilities a user has when it comes to directly pulling out money with say a bank transfer. 
  day_of_birth          String    // Not needed for Stripe Connected Account?
  country_of_residence   String

  @@map("connected_accounts")
}

model Family {
  cuid                 String      @id @default(cuid())
  Stripe_Account       ConnectedAccount?    @relation(fields: [Stripe_Account_id], references: cuid)
  Stripe_Account_id     String?
  family_members       User[]
  possible_first_user  User?
  advocate_responsible User
  family_relationship   String
  family_role           String
  created_at            String      @default(now().toString())
  updated_at            String
  Pages                Page[]
  PageDonations        PageDonation[]
  DonationPayouts      DonationPayout[]
}

**Comment by OfekShaltiel-UTD** [comment]
1. How should we select a family using a selector such as a listbox, do we show the last name of a user or should there be a name field for the family itself on the first user?

**Comment by OfekShaltiel-UTD** [comment]
@pariahGH 
1. Should we add a table to display every family and its users or is this under the jurisdiction of the reports table?
2. Should a page being edited or created be assigned a family in the EditPage workflow (if say an advocate is creating it) via a select structure (or equivalently a listbox)?

**Comment by OfekShaltiel-UTD** [comment]
1. Should the page list for each family member contain the aggregate pages of the family and the page list for advocates is the pages they've created?
